### ISSUE TITLE
windows下mingw无法编译通过

### ISSUE THREAD

**Issue by renpeng009** [zlgopen/awtk-scons-mingw#1]
环境：win7x64 + awtk-scons-mingw
编译结果：
src\\platforms\\pc\\fs_os.c: In function 'fs_os_file_exist':\nsrc\\platforms\\pc\\fs_os.c:189:21: error: storage size of 'st' isn't known\n   struct _stat64i32 st;
src\\platforms\\pc\\fs_os.c: In function 'fs_os_dir_exist':\nsrc\\platforms\\pc\\fs_os.c:296:21: error: storage size of 'st' isn't known\n   struct _stat64i32 st;
src\\platforms\\pc\\fs_os.c: In function 'fs_os_get_file_size':\nsrc\\platforms\\pc\\fs_os.c:327:21: error: storage size of 'st' isn't known\n   struct _stat64i32 st;
src\\platforms\\pc\\fs_os.c: In function 'fs_os_stat':\nsrc\\platforms\\pc\\fs_os.c:405:21: error: storage size of 'st' isn't known\n   struct _stat64i32 st;

安装环境均按照官方要求来的，请问如何解决？

**Comment by sosotan** [comment]
已经修正好, 麻烦下载最新的awtk试试

**Comment by renpeng009** [comment]
> 已经修正好, 麻烦下载最新的awtk试试

事实上我已经自己修正了所有编译不过去的”坑“(*^^)v
所有的记录都写在https://blog.csdn.net/renpeng009672/article/details/106156150
但是还没等我写完你们就修复了(*￣︶￣)y
搞得我都不知道该不该继续写了(눈_눈)
哈哈
